/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2ContactImpulse
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** Set attributes (key, value)
 * 
 */
static int b2ContactImpulse__set_(lua_State *L) {

  b2ContactImpulse *self = *((b2ContactImpulse **)dub::checksdata_n(L, 1, "b2.b2ContactImpulse"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "count")) break;
      self->count = luaL_checkint(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2ContactImpulse__get_(lua_State *L) {

  b2ContactImpulse *self = *((b2ContactImpulse **)dub::checksdata_n(L, 1, "b2.b2ContactImpulse", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "count")) break;
      lua_pushnumber(L, self->count);
      return 1;
    }
  }
  return 0;
}

/** b2ContactImpulse()
 * 
 */
static int b2ContactImpulse_b2ContactImpulse(lua_State *L) {
  try {
    b2ContactImpulse *retval__ = new b2ContactImpulse();
    dub::pushudata(L, retval__, "b2.b2ContactImpulse", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** Read normalImpulses(size_t i)
 * 
 */
static int b2ContactImpulse_normalImpulses(lua_State *L) {
  try {
    b2ContactImpulse *self = *((b2ContactImpulse **)dub::checksdata(L, 1, "b2.b2ContactImpulse"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      size_t i = dub::checkint(L, 2);
      float32 v = dub::checknumber(L, 3);
      if (!i || i > b2_maxManifoldPoints) return 0;
      self->normalImpulses[i-1] = v;
      return 0;
    } else {
      size_t i = dub::checkint(L, 2);
      if (!i || i > b2_maxManifoldPoints) return 0;
      lua_pushnumber(L, self->normalImpulses[i-1]);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "normalImpulses: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "normalImpulses: Unknown exception");
  }
  return dub::error(L);
}

/** Read tangentImpulses(size_t i)
 * 
 */
static int b2ContactImpulse_tangentImpulses(lua_State *L) {
  try {
    b2ContactImpulse *self = *((b2ContactImpulse **)dub::checksdata(L, 1, "b2.b2ContactImpulse"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      size_t i = dub::checkint(L, 2);
      float32 v = dub::checknumber(L, 3);
      if (!i || i > b2_maxManifoldPoints) return 0;
      self->tangentImpulses[i-1] = v;
      return 0;
    } else {
      size_t i = dub::checkint(L, 2);
      if (!i || i > b2_maxManifoldPoints) return 0;
      lua_pushnumber(L, self->tangentImpulses[i-1]);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "tangentImpulses: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "tangentImpulses: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2ContactImpulse___tostring(lua_State *L) {
  b2ContactImpulse *self = *((b2ContactImpulse **)dub::checksdata_n(L, 1, "b2.b2ContactImpulse"));
  lua_pushfstring(L, "b2.b2ContactImpulse: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2ContactImpulse_member_methods[] = {
  { "__newindex"   , b2ContactImpulse__set_ },
  { "__index"      , b2ContactImpulse__get_ },
  { "new"          , b2ContactImpulse_b2ContactImpulse },
  { "normalImpulses", b2ContactImpulse_normalImpulses },
  { "tangentImpulses", b2ContactImpulse_tangentImpulses },
  { "__tostring"   , b2ContactImpulse___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2ContactImpulse(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2ContactImpulse");
  // <mt>

  // register member methods
  dub::fregister(L, b2ContactImpulse_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2ContactImpulse");
  // <mt>
  return 1;
}
