/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2RopeDef
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Rope/b2Rope.h>


/** ~b2RopeDef()
 * 
 */
static int b2RopeDef__b2RopeDef(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "b2.b2RopeDef"));
    if (userdata->gc) {
      b2RopeDef *self = (b2RopeDef *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** Set attributes (key, value)
 * 
 */
static int b2RopeDef__set_(lua_State *L) {

  b2RopeDef *self = *((b2RopeDef **)dub::checksdata_n(L, 1, "b2.b2RopeDef"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 11);
  switch(key_h) {
    case 4: {
      if (DUB_ASSERT_KEY(key, "vertices")) break;
      dub::protect(L, 1, 3, "vertices");
      self->vertices = *((b2Vec2 **)dub::checksdata_n(L, 3, "b2.b2Vec2"));
      return 0;
    }
    case 9: {
      if (DUB_ASSERT_KEY(key, "count")) break;
      self->count = luaL_checkint(L, 3);
      return 0;
    }
    case 7: {
      if (DUB_ASSERT_KEY(key, "masses")) break;
      dub::protect(L, 1, 3, "masses");
      self->masses = *((float32 **)dub::checksdata_n(L, 3, "float32"));
      return 0;
    }
    case 6: {
      if (DUB_ASSERT_KEY(key, "gravity")) break;
      self->gravity = **((b2Vec2 **)dub::checksdata_n(L, 3, "b2.b2Vec2"));
      return 0;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "damping")) break;
      self->damping = luaL_checknumber(L, 3);
      return 0;
    }
    case 10: {
      if (DUB_ASSERT_KEY(key, "k2")) break;
      self->k2 = luaL_checknumber(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "k3")) break;
      self->k3 = luaL_checknumber(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2RopeDef__get_(lua_State *L) {

  b2RopeDef *self = *((b2RopeDef **)dub::checksdata_n(L, 1, "b2.b2RopeDef", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 11);
  switch(key_h) {
    case 4: {
      if (DUB_ASSERT_KEY(key, "vertices")) break;
      b2Vec2 *retval__ = self->vertices;
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "b2.b2Vec2", false);
      return 1;
    }
    case 9: {
      if (DUB_ASSERT_KEY(key, "count")) break;
      lua_pushnumber(L, self->count);
      return 1;
    }
    case 7: {
      if (DUB_ASSERT_KEY(key, "masses")) break;
      float32 *retval__ = self->masses;
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "float32", false);
      return 1;
    }
    case 6: {
      if (DUB_ASSERT_KEY(key, "gravity")) break;
      dub::pushudata(L, &self->gravity, "b2.b2Vec2", false);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "damping")) break;
      lua_pushnumber(L, self->damping);
      return 1;
    }
    case 10: {
      if (DUB_ASSERT_KEY(key, "k2")) break;
      lua_pushnumber(L, self->k2);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "k3")) break;
      lua_pushnumber(L, self->k3);
      return 1;
    }
  }
  return 0;
}

/** b2RopeDef::b2RopeDef()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Rope/b2Rope.h:29
 */
static int b2RopeDef_b2RopeDef(lua_State *L) {
  try {
    b2RopeDef *retval__ = new b2RopeDef();
    dub::pushudata(L, retval__, "b2.b2RopeDef", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2RopeDef___tostring(lua_State *L) {
  b2RopeDef *self = *((b2RopeDef **)dub::checksdata_n(L, 1, "b2.b2RopeDef"));
  lua_pushfstring(L, "b2.b2RopeDef: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2RopeDef_member_methods[] = {
  { "__gc"         , b2RopeDef__b2RopeDef },
  { "__newindex"   , b2RopeDef__set_      },
  { "__index"      , b2RopeDef__get_      },
  { "new"          , b2RopeDef_b2RopeDef  },
  { "__tostring"   , b2RopeDef___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2RopeDef(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2RopeDef");
  // <mt>

  // register member methods
  dub::fregister(L, b2RopeDef_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2RopeDef");
  // <mt>
  return 1;
}
