/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2ContactFilter
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** b2ContactFilter()
 * 
 */
static int b2ContactFilter_b2ContactFilter(lua_State *L) {
  try {
    b2ContactFilter *retval__ = new b2ContactFilter();
    dub::pushudata(L, retval__, "b2.b2ContactFilter", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** virtual b2ContactFilter::~b2ContactFilter()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/b2WorldCallbacks.h:55
 */
static int b2ContactFilter__b2ContactFilter(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "b2.b2ContactFilter"));
    if (userdata->gc) {
      b2ContactFilter *self = (b2ContactFilter *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** bool b2ContactFilter::ShouldCollide(b2Fixture *fixtureA, b2Fixture *fixtureB)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/b2WorldCallbacks.h:59
 */
static int b2ContactFilter_ShouldCollide(lua_State *L) {
  try {
    b2ContactFilter *self = *((b2ContactFilter **)dub::checksdata(L, 1, "b2.b2ContactFilter"));
    b2Fixture *fixtureA = *((b2Fixture **)dub::checksdata(L, 2, "b2.b2Fixture"));
    b2Fixture *fixtureB = *((b2Fixture **)dub::checksdata(L, 3, "b2.b2Fixture"));
    lua_pushboolean(L, self->ShouldCollide(fixtureA, fixtureB));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "ShouldCollide: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "ShouldCollide: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2ContactFilter___tostring(lua_State *L) {
  b2ContactFilter *self = *((b2ContactFilter **)dub::checksdata_n(L, 1, "b2.b2ContactFilter"));
  lua_pushfstring(L, "b2.b2ContactFilter: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2ContactFilter_member_methods[] = {
  { "new"          , b2ContactFilter_b2ContactFilter },
  { "__gc"         , b2ContactFilter__b2ContactFilter },
  { "ShouldCollide", b2ContactFilter_ShouldCollide },
  { "__tostring"   , b2ContactFilter___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2ContactFilter(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2ContactFilter");
  // <mt>

  // register member methods
  dub::fregister(L, b2ContactFilter_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2ContactFilter");
  // <mt>
  return 1;
}
