/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2BlockAllocator
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** b2BlockAllocator::b2BlockAllocator()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Common/b2BlockAllocator.h:38
 */
static int b2BlockAllocator_b2BlockAllocator(lua_State *L) {
  try {
    b2BlockAllocator *retval__ = new b2BlockAllocator();
    dub::pushudata(L, retval__, "b2.b2BlockAllocator", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** b2BlockAllocator::~b2BlockAllocator()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Common/b2BlockAllocator.h:39
 */
static int b2BlockAllocator__b2BlockAllocator(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "b2.b2BlockAllocator"));
    if (userdata->gc) {
      b2BlockAllocator *self = (b2BlockAllocator *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** void * b2BlockAllocator::Allocate(int32 size)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Common/b2BlockAllocator.h:42
 */
static int b2BlockAllocator_Allocate(lua_State *L) {
  try {
    b2BlockAllocator *self = *((b2BlockAllocator **)dub::checksdata(L, 1, "b2.b2BlockAllocator"));
    int32 size = dub::checkint(L, 2);
    self->Allocate(size);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Allocate: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Allocate: Unknown exception");
  }
  return dub::error(L);
}

/** void b2BlockAllocator::Free(void *p, int32 size)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Common/b2BlockAllocator.h:45
 */
static int b2BlockAllocator_Free(lua_State *L) {
  try {
    b2BlockAllocator *self = *((b2BlockAllocator **)dub::checksdata(L, 1, "b2.b2BlockAllocator"));
    void *p = *((void **)dub::checksdata(L, 2, "void"));
    int32 size = dub::checkint(L, 3);
    self->Free(p, size);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Free: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Free: Unknown exception");
  }
  return dub::error(L);
}

/** void b2BlockAllocator::Clear()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Common/b2BlockAllocator.h:47
 */
static int b2BlockAllocator_Clear(lua_State *L) {
  try {
    b2BlockAllocator *self = *((b2BlockAllocator **)dub::checksdata(L, 1, "b2.b2BlockAllocator"));
    self->Clear();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Clear: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Clear: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2BlockAllocator___tostring(lua_State *L) {
  b2BlockAllocator *self = *((b2BlockAllocator **)dub::checksdata_n(L, 1, "b2.b2BlockAllocator"));
  lua_pushfstring(L, "b2.b2BlockAllocator: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2BlockAllocator_member_methods[] = {
  { "new"          , b2BlockAllocator_b2BlockAllocator },
  { "__gc"         , b2BlockAllocator__b2BlockAllocator },
  { "Allocate"     , b2BlockAllocator_Allocate },
  { "Free"         , b2BlockAllocator_Free },
  { "Clear"        , b2BlockAllocator_Clear },
  { "__tostring"   , b2BlockAllocator___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2BlockAllocator(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2BlockAllocator");
  // <mt>

  // register member methods
  dub::fregister(L, b2BlockAllocator_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2BlockAllocator");
  // <mt>
  return 1;
}
