/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2StackEntry
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** Set attributes (key, value)
 * 
 */
static int b2StackEntry__set_(lua_State *L) {

  b2StackEntry *self = *((b2StackEntry **)dub::checksdata_n(L, 1, "b2.b2StackEntry"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 3);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "data")) break;
      self->data = luaL_checkstring(L, 3);
      return 0;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "size")) break;
      self->size = luaL_checkint(L, 3);
      return 0;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "usedMalloc")) break;
      self->usedMalloc = luaL_checkboolean(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2StackEntry__get_(lua_State *L) {

  b2StackEntry *self = *((b2StackEntry **)dub::checksdata_n(L, 1, "b2.b2StackEntry", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 3);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "data")) break;
      lua_pushstring(L, self->data);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "size")) break;
      lua_pushnumber(L, self->size);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "usedMalloc")) break;
      lua_pushboolean(L, self->usedMalloc);
      return 1;
    }
  }
  return 0;
}

/** b2StackEntry()
 * 
 */
static int b2StackEntry_b2StackEntry(lua_State *L) {
  try {
    b2StackEntry *retval__ = new b2StackEntry();
    dub::pushudata(L, retval__, "b2.b2StackEntry", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2StackEntry___tostring(lua_State *L) {
  b2StackEntry *self = *((b2StackEntry **)dub::checksdata_n(L, 1, "b2.b2StackEntry"));
  lua_pushfstring(L, "b2.b2StackEntry: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2StackEntry_member_methods[] = {
  { "__newindex"   , b2StackEntry__set_   },
  { "__index"      , b2StackEntry__get_   },
  { "new"          , b2StackEntry_b2StackEntry },
  { "__tostring"   , b2StackEntry___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2StackEntry(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2StackEntry");
  // <mt>

  // register member methods
  dub::fregister(L, b2StackEntry_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2StackEntry");
  // <mt>
  return 1;
}
