/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2FixtureDef
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** ~b2FixtureDef()
 * 
 */
static int b2FixtureDef__b2FixtureDef(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "b2.b2FixtureDef"));
    if (userdata->gc) {
      b2FixtureDef *self = (b2FixtureDef *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** Set attributes (key, value)
 * 
 */
static int b2FixtureDef__set_(lua_State *L) {

  b2FixtureDef *self = *((b2FixtureDef **)dub::checksdata_n(L, 1, "b2.b2FixtureDef"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 17);
  switch(key_h) {
    case 9: {
      if (DUB_ASSERT_KEY(key, "shape")) break;
      dub::protect(L, 1, 3, "shape");
      self->shape = *((b2Shape **)dub::checksdata_n(L, 3, "b2.b2Shape"));
      return 0;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "userData")) break;
      dub::protect(L, 1, 3, "userData");
      self->userData = *((void **)dub::checksdata_n(L, 3, "void"));
      return 0;
    }
    case 6: {
      if (DUB_ASSERT_KEY(key, "friction")) break;
      self->friction = luaL_checknumber(L, 3);
      return 0;
    }
    case 12: {
      if (DUB_ASSERT_KEY(key, "restitution")) break;
      self->restitution = luaL_checknumber(L, 3);
      return 0;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "density")) break;
      self->density = luaL_checknumber(L, 3);
      return 0;
    }
    case 14: {
      if (DUB_ASSERT_KEY(key, "isSensor")) break;
      self->isSensor = luaL_checkboolean(L, 3);
      return 0;
    }
    case 13: {
      if (DUB_ASSERT_KEY(key, "filter")) break;
      self->filter = **((b2Filter **)dub::checksdata_n(L, 3, "b2.b2Filter"));
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2FixtureDef__get_(lua_State *L) {

  b2FixtureDef *self = *((b2FixtureDef **)dub::checksdata_n(L, 1, "b2.b2FixtureDef", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 17);
  switch(key_h) {
    case 9: {
      if (DUB_ASSERT_KEY(key, "shape")) break;
      const b2Shape *retval__ = self->shape;
      if (!retval__) return 0;
      dub::pushudata(L, const_cast<b2Shape*>(retval__), "b2.b2Shape", false);
      return 1;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "userData")) break;
      void *retval__ = self->userData;
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "void", false);
      return 1;
    }
    case 6: {
      if (DUB_ASSERT_KEY(key, "friction")) break;
      lua_pushnumber(L, self->friction);
      return 1;
    }
    case 12: {
      if (DUB_ASSERT_KEY(key, "restitution")) break;
      lua_pushnumber(L, self->restitution);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "density")) break;
      lua_pushnumber(L, self->density);
      return 1;
    }
    case 14: {
      if (DUB_ASSERT_KEY(key, "isSensor")) break;
      lua_pushboolean(L, self->isSensor);
      return 1;
    }
    case 13: {
      if (DUB_ASSERT_KEY(key, "filter")) break;
      dub::pushudata(L, &self->filter, "b2.b2Filter", false);
      return 1;
    }
  }
  return 0;
}

/** b2FixtureDef::b2FixtureDef()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/b2Fixture.h:59
 */
static int b2FixtureDef_b2FixtureDef(lua_State *L) {
  try {
    b2FixtureDef *retval__ = new b2FixtureDef();
    dub::pushudata(L, retval__, "b2.b2FixtureDef", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2FixtureDef___tostring(lua_State *L) {
  b2FixtureDef *self = *((b2FixtureDef **)dub::checksdata_n(L, 1, "b2.b2FixtureDef"));
  lua_pushfstring(L, "b2.b2FixtureDef: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2FixtureDef_member_methods[] = {
  { "__gc"         , b2FixtureDef__b2FixtureDef },
  { "__newindex"   , b2FixtureDef__set_   },
  { "__index"      , b2FixtureDef__get_   },
  { "new"          , b2FixtureDef_b2FixtureDef },
  { "__tostring"   , b2FixtureDef___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2FixtureDef(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2FixtureDef");
  // <mt>

  // register member methods
  dub::fregister(L, b2FixtureDef_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2FixtureDef");
  // <mt>
  return 1;
}
