/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2ContactID
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** Set attributes (key, value)
 * 
 */
static int b2ContactID__set_(lua_State *L) {

  b2ContactID *self = *((b2ContactID **)dub::checksdata_n(L, 1, "b2.b2ContactID"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 5);
  switch(key_h) {
    case 3: {
      if (DUB_ASSERT_KEY(key, "cf")) break;
      self->cf = **((b2ContactFeature **)dub::checksdata_n(L, 3, "b2.b2ContactFeature"));
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "key")) break;
      self->key = luaL_checkint(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2ContactID__get_(lua_State *L) {

  b2ContactID *self = *((b2ContactID **)dub::checksdata_n(L, 1, "b2.b2ContactID", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 5);
  switch(key_h) {
    case 3: {
      if (DUB_ASSERT_KEY(key, "cf")) break;
      dub::pushudata(L, &self->cf, "b2.b2ContactFeature", false);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "key")) break;
      lua_pushnumber(L, self->key);
      return 1;
    }
  }
  return 0;
}

/** b2ContactID()
 * 
 */
static int b2ContactID_b2ContactID(lua_State *L) {
  try {
    b2ContactID *retval__ = new b2ContactID();
    dub::pushudata(L, retval__, "b2.b2ContactID", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2ContactID___tostring(lua_State *L) {
  b2ContactID *self = *((b2ContactID **)dub::checksdata_n(L, 1, "b2.b2ContactID"));
  lua_pushfstring(L, "b2.b2ContactID: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2ContactID_member_methods[] = {
  { "__newindex"   , b2ContactID__set_    },
  { "__index"      , b2ContactID__get_    },
  { "new"          , b2ContactID_b2ContactID },
  { "__tostring"   , b2ContactID___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2ContactID(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2ContactID");
  // <mt>

  // register member methods
  dub::fregister(L, b2ContactID_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2ContactID");
  // <mt>
  return 1;
}
