/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2RayCastOutput
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** Set attributes (key, value)
 * 
 */
static int b2RayCastOutput__set_(lua_State *L) {

  b2RayCastOutput *self = *((b2RayCastOutput **)dub::checksdata_n(L, 1, "b2.b2RayCastOutput"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "normal")) break;
      self->normal = **((b2Vec2 **)dub::checksdata_n(L, 3, "b2.b2Vec2"));
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "fraction")) break;
      self->fraction = luaL_checknumber(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2RayCastOutput__get_(lua_State *L) {

  b2RayCastOutput *self = *((b2RayCastOutput **)dub::checksdata_n(L, 1, "b2.b2RayCastOutput", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "normal")) break;
      dub::pushudata(L, &self->normal, "b2.b2Vec2", false);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "fraction")) break;
      lua_pushnumber(L, self->fraction);
      return 1;
    }
  }
  return 0;
}

/** b2RayCastOutput()
 * 
 */
static int b2RayCastOutput_b2RayCastOutput(lua_State *L) {
  try {
    b2RayCastOutput *retval__ = new b2RayCastOutput();
    dub::pushudata(L, retval__, "b2.b2RayCastOutput", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2RayCastOutput___tostring(lua_State *L) {
  b2RayCastOutput *self = *((b2RayCastOutput **)dub::checksdata_n(L, 1, "b2.b2RayCastOutput"));
  lua_pushfstring(L, "b2.b2RayCastOutput: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2RayCastOutput_member_methods[] = {
  { "__newindex"   , b2RayCastOutput__set_ },
  { "__index"      , b2RayCastOutput__get_ },
  { "new"          , b2RayCastOutput_b2RayCastOutput },
  { "__tostring"   , b2RayCastOutput___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2RayCastOutput(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2RayCastOutput");
  // <mt>

  // register member methods
  dub::fregister(L, b2RayCastOutput_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2RayCastOutput");
  // <mt>
  return 1;
}
