/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2MotorJoint
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** ~b2MotorJoint()
 * 
 */
static int b2MotorJoint__b2MotorJoint(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "b2.b2MotorJoint"));
    if (userdata->gc) {
      b2MotorJoint *self = (b2MotorJoint *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** Cast (class_name)
 * 
 */
static int b2MotorJoint__cast_(lua_State *L) {

  b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata_n(L, 1, "b2.b2MotorJoint"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub::hash(key, 2);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "b2.b2Joint")) break;
      *retval__ = static_cast<b2Joint *>(self);
      return 1;
    }
  }
  return 0;
}

/** b2Vec2 b2MotorJoint::GetAnchorA() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:62
 */
static int b2MotorJoint_GetAnchorA(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    dub::pushudata(L, new b2Vec2(self->GetAnchorA()), "b2.b2Vec2", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetAnchorA: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetAnchorA: Unknown exception");
  }
  return dub::error(L);
}

/** b2Vec2 b2MotorJoint::GetAnchorB() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:63
 */
static int b2MotorJoint_GetAnchorB(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    dub::pushudata(L, new b2Vec2(self->GetAnchorB()), "b2.b2Vec2", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetAnchorB: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetAnchorB: Unknown exception");
  }
  return dub::error(L);
}

/** b2Vec2 b2MotorJoint::GetReactionForce(float32 inv_dt) const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:65
 */
static int b2MotorJoint_GetReactionForce(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    float32 inv_dt = dub::checknumber(L, 2);
    dub::pushudata(L, new b2Vec2(self->GetReactionForce(inv_dt)), "b2.b2Vec2", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetReactionForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetReactionForce: Unknown exception");
  }
  return dub::error(L);
}

/** float32 b2MotorJoint::GetReactionTorque(float32 inv_dt) const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:66
 */
static int b2MotorJoint_GetReactionTorque(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    float32 inv_dt = dub::checknumber(L, 2);
    lua_pushnumber(L, self->GetReactionTorque(inv_dt));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetReactionTorque: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetReactionTorque: Unknown exception");
  }
  return dub::error(L);
}

/** void b2MotorJoint::SetLinearOffset(const b2Vec2 &linearOffset)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:69
 */
static int b2MotorJoint_SetLinearOffset(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    b2Vec2 *linearOffset = *((b2Vec2 **)dub::checksdata(L, 2, "b2.b2Vec2"));
    self->SetLinearOffset(*linearOffset);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetLinearOffset: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetLinearOffset: Unknown exception");
  }
  return dub::error(L);
}

/** const b2Vec2 & b2MotorJoint::GetLinearOffset() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:70
 */
static int b2MotorJoint_GetLinearOffset(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    dub::pushudata(L, const_cast<b2Vec2*>(&self->GetLinearOffset()), "b2.b2Vec2", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetLinearOffset: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetLinearOffset: Unknown exception");
  }
  return dub::error(L);
}

/** void b2MotorJoint::SetAngularOffset(float32 angularOffset)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:73
 */
static int b2MotorJoint_SetAngularOffset(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    float32 angularOffset = dub::checknumber(L, 2);
    self->SetAngularOffset(angularOffset);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetAngularOffset: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetAngularOffset: Unknown exception");
  }
  return dub::error(L);
}

/** float32 b2MotorJoint::GetAngularOffset() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:74
 */
static int b2MotorJoint_GetAngularOffset(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    lua_pushnumber(L, self->GetAngularOffset());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetAngularOffset: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetAngularOffset: Unknown exception");
  }
  return dub::error(L);
}

/** void b2MotorJoint::SetMaxForce(float32 force)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:77
 */
static int b2MotorJoint_SetMaxForce(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    float32 force = dub::checknumber(L, 2);
    self->SetMaxForce(force);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetMaxForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetMaxForce: Unknown exception");
  }
  return dub::error(L);
}

/** float32 b2MotorJoint::GetMaxForce() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:80
 */
static int b2MotorJoint_GetMaxForce(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    lua_pushnumber(L, self->GetMaxForce());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetMaxForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetMaxForce: Unknown exception");
  }
  return dub::error(L);
}

/** void b2MotorJoint::SetMaxTorque(float32 torque)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:83
 */
static int b2MotorJoint_SetMaxTorque(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    float32 torque = dub::checknumber(L, 2);
    self->SetMaxTorque(torque);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetMaxTorque: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetMaxTorque: Unknown exception");
  }
  return dub::error(L);
}

/** float32 b2MotorJoint::GetMaxTorque() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:86
 */
static int b2MotorJoint_GetMaxTorque(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    lua_pushnumber(L, self->GetMaxTorque());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetMaxTorque: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetMaxTorque: Unknown exception");
  }
  return dub::error(L);
}

/** void b2MotorJoint::SetCorrectionFactor(float32 factor)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:89
 */
static int b2MotorJoint_SetCorrectionFactor(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    float32 factor = dub::checknumber(L, 2);
    self->SetCorrectionFactor(factor);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetCorrectionFactor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetCorrectionFactor: Unknown exception");
  }
  return dub::error(L);
}

/** float32 b2MotorJoint::GetCorrectionFactor() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:92
 */
static int b2MotorJoint_GetCorrectionFactor(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    lua_pushnumber(L, self->GetCorrectionFactor());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetCorrectionFactor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetCorrectionFactor: Unknown exception");
  }
  return dub::error(L);
}

/** void b2MotorJoint::Dump()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.h:95
 */
static int b2MotorJoint_Dump(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    self->Dump();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Dump: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Dump: Unknown exception");
  }
  return dub::error(L);
}

/** b2JointType b2Joint::GetType() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:108
 */
static int b2MotorJoint_GetType(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    lua_pushnumber(L, self->GetType());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetType: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetType: Unknown exception");
  }
  return dub::error(L);
}

/** b2Body * b2Joint::GetBodyA()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:111
 */
static int b2MotorJoint_GetBodyA(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    b2Body *retval__ = self->GetBodyA();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "b2.b2Body", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetBodyA: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetBodyA: Unknown exception");
  }
  return dub::error(L);
}

/** b2Body * b2Joint::GetBodyB()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:114
 */
static int b2MotorJoint_GetBodyB(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    b2Body *retval__ = self->GetBodyB();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "b2.b2Body", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetBodyB: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetBodyB: Unknown exception");
  }
  return dub::error(L);
}

/** b2Joint * b2Joint::GetNext()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:129
 */
static int b2MotorJoint_GetNext(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    b2Joint *retval__ = self->GetNext();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "b2.b2Joint", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetNext: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetNext: Unknown exception");
  }
  return dub::error(L);
}

/** void * b2Joint::GetUserData() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:133
 */
static int b2MotorJoint_GetUserData(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    self->GetUserData();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetUserData: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetUserData: Unknown exception");
  }
  return dub::error(L);
}

/** void b2Joint::SetUserData(void *data)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:136
 */
static int b2MotorJoint_SetUserData(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    void *data = *((void **)dub::checksdata(L, 2, "void"));
    self->SetUserData(data);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "SetUserData: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SetUserData: Unknown exception");
  }
  return dub::error(L);
}

/** bool b2Joint::IsActive() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:139
 */
static int b2MotorJoint_IsActive(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    lua_pushboolean(L, self->IsActive());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "IsActive: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "IsActive: Unknown exception");
  }
  return dub::error(L);
}

/** bool b2Joint::GetCollideConnected() const
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:144
 */
static int b2MotorJoint_GetCollideConnected(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    lua_pushboolean(L, self->GetCollideConnected());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "GetCollideConnected: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "GetCollideConnected: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void b2Joint::ShiftOrigin(const b2Vec2 &newOrigin)
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/Joints/b2Joint.h:150
 */
static int b2MotorJoint_ShiftOrigin(lua_State *L) {
  try {
    b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata(L, 1, "b2.b2MotorJoint"));
    b2Vec2 *newOrigin = *((b2Vec2 **)dub::checksdata(L, 2, "b2.b2Vec2"));
    self->ShiftOrigin(*newOrigin);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "ShiftOrigin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "ShiftOrigin: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2MotorJoint___tostring(lua_State *L) {
  b2MotorJoint *self = *((b2MotorJoint **)dub::checksdata_n(L, 1, "b2.b2MotorJoint"));
  lua_pushfstring(L, "b2.b2MotorJoint: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2MotorJoint_member_methods[] = {
  { "__gc"         , b2MotorJoint__b2MotorJoint },
  { "_cast_"       , b2MotorJoint__cast_  },
  { "GetAnchorA"   , b2MotorJoint_GetAnchorA },
  { "GetAnchorB"   , b2MotorJoint_GetAnchorB },
  { "GetReactionForce", b2MotorJoint_GetReactionForce },
  { "GetReactionTorque", b2MotorJoint_GetReactionTorque },
  { "SetLinearOffset", b2MotorJoint_SetLinearOffset },
  { "GetLinearOffset", b2MotorJoint_GetLinearOffset },
  { "SetAngularOffset", b2MotorJoint_SetAngularOffset },
  { "GetAngularOffset", b2MotorJoint_GetAngularOffset },
  { "SetMaxForce"  , b2MotorJoint_SetMaxForce },
  { "GetMaxForce"  , b2MotorJoint_GetMaxForce },
  { "SetMaxTorque" , b2MotorJoint_SetMaxTorque },
  { "GetMaxTorque" , b2MotorJoint_GetMaxTorque },
  { "SetCorrectionFactor", b2MotorJoint_SetCorrectionFactor },
  { "GetCorrectionFactor", b2MotorJoint_GetCorrectionFactor },
  { "Dump"         , b2MotorJoint_Dump    },
  { "GetType"      , b2MotorJoint_GetType },
  { "GetBodyA"     , b2MotorJoint_GetBodyA },
  { "GetBodyB"     , b2MotorJoint_GetBodyB },
  { "GetNext"      , b2MotorJoint_GetNext },
  { "GetUserData"  , b2MotorJoint_GetUserData },
  { "SetUserData"  , b2MotorJoint_SetUserData },
  { "IsActive"     , b2MotorJoint_IsActive },
  { "GetCollideConnected", b2MotorJoint_GetCollideConnected },
  { "ShiftOrigin"  , b2MotorJoint_ShiftOrigin },
  { "__tostring"   , b2MotorJoint___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2MotorJoint(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2MotorJoint");
  // <mt>

  // register member methods
  dub::fregister(L, b2MotorJoint_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2MotorJoint");
  // <mt>
  return 1;
}
