/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2JointEdge
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** Set attributes (key, value)
 * 
 */
static int b2JointEdge__set_(lua_State *L) {

  b2JointEdge *self = *((b2JointEdge **)dub::checksdata_n(L, 1, "b2.b2JointEdge"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 6);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "other")) break;
      dub::protect(L, 1, 3, "other");
      self->other = *((b2Body **)dub::checksdata_n(L, 3, "b2.b2Body"));
      return 0;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "joint")) break;
      dub::protect(L, 1, 3, "joint");
      self->joint = *((b2Joint **)dub::checksdata_n(L, 3, "b2.b2Joint"));
      return 0;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "prev")) break;
      dub::protect(L, 1, 3, "prev");
      self->prev = *((b2JointEdge **)dub::checksdata_n(L, 3, "b2.b2JointEdge"));
      return 0;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "next")) break;
      dub::protect(L, 1, 3, "next");
      self->next = *((b2JointEdge **)dub::checksdata_n(L, 3, "b2.b2JointEdge"));
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2JointEdge__get_(lua_State *L) {

  b2JointEdge *self = *((b2JointEdge **)dub::checksdata_n(L, 1, "b2.b2JointEdge", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 6);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "other")) break;
      b2Body *retval__ = self->other;
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "b2.b2Body", false);
      return 1;
    }
    case 4: {
      if (DUB_ASSERT_KEY(key, "joint")) break;
      b2Joint *retval__ = self->joint;
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "b2.b2Joint", false);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "prev")) break;
      b2JointEdge *retval__ = self->prev;
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "b2.b2JointEdge", false);
      return 1;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "next")) break;
      b2JointEdge *retval__ = self->next;
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "b2.b2JointEdge", false);
      return 1;
    }
  }
  return 0;
}

/** b2JointEdge()
 * 
 */
static int b2JointEdge_b2JointEdge(lua_State *L) {
  try {
    b2JointEdge *retval__ = new b2JointEdge();
    dub::pushudata(L, retval__, "b2.b2JointEdge", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2JointEdge___tostring(lua_State *L) {
  b2JointEdge *self = *((b2JointEdge **)dub::checksdata_n(L, 1, "b2.b2JointEdge"));
  lua_pushfstring(L, "b2.b2JointEdge: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2JointEdge_member_methods[] = {
  { "__newindex"   , b2JointEdge__set_    },
  { "__index"      , b2JointEdge__get_    },
  { "new"          , b2JointEdge_b2JointEdge },
  { "__tostring"   , b2JointEdge___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2JointEdge(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2JointEdge");
  // <mt>

  // register member methods
  dub::fregister(L, b2JointEdge_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2JointEdge");
  // <mt>
  return 1;
}
