/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2Filter
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** ~b2Filter()
 * 
 */
static int b2Filter__b2Filter(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "b2.b2Filter"));
    if (userdata->gc) {
      b2Filter *self = (b2Filter *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** Set attributes (key, value)
 * 
 */
static int b2Filter__set_(lua_State *L) {

  b2Filter *self = *((b2Filter **)dub::checksdata_n(L, 1, "b2.b2Filter"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub::hash(key, 4);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "categoryBits")) break;
      self->categoryBits = luaL_checkint(L, 3);
      return 0;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "maskBits")) break;
      self->maskBits = luaL_checkint(L, 3);
      return 0;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "groupIndex")) break;
      self->groupIndex = luaL_checkint(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int b2Filter__get_(lua_State *L) {

  b2Filter *self = *((b2Filter **)dub::checksdata_n(L, 1, "b2.b2Filter", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub::hash(key, 4);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "categoryBits")) break;
      lua_pushnumber(L, self->categoryBits);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "maskBits")) break;
      lua_pushnumber(L, self->maskBits);
      return 1;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "groupIndex")) break;
      lua_pushnumber(L, self->groupIndex);
      return 1;
    }
  }
  return 0;
}

/** b2Filter::b2Filter()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/b2Fixture.h:34
 */
static int b2Filter_b2Filter(lua_State *L) {
  try {
    b2Filter *retval__ = new b2Filter();
    dub::pushudata(L, retval__, "b2.b2Filter", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2Filter___tostring(lua_State *L) {
  b2Filter *self = *((b2Filter **)dub::checksdata_n(L, 1, "b2.b2Filter"));
  lua_pushfstring(L, "b2.b2Filter: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2Filter_member_methods[] = {
  { "__gc"         , b2Filter__b2Filter   },
  { "__newindex"   , b2Filter__set_       },
  { "__index"      , b2Filter__get_       },
  { "new"          , b2Filter_b2Filter    },
  { "__tostring"   , b2Filter___tostring  },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2Filter(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2Filter");
  // <mt>

  // register member methods
  dub::fregister(L, b2Filter_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2Filter");
  // <mt>
  return 1;
}
