/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class b2DestructionListener
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include <Box2D/Box2D.h>


/** virtual b2DestructionListener::~b2DestructionListener()
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/b2WorldCallbacks.h:39
 */
static int b2DestructionListener__b2DestructionListener(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "b2.b2DestructionListener"));
    if (userdata->gc) {
      b2DestructionListener *self = (b2DestructionListener *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void b2DestructionListener::SayGoodbye(b2Joint *joint)=0
 * /media/sundeep/3 tb Vol/code/Clone-game-repo/Clone-game/vendor/Box2D/Box2D/Dynamics/b2WorldCallbacks.h:43
 */
static int b2DestructionListener_SayGoodbye(lua_State *L) {
  try {
    b2DestructionListener *self = *((b2DestructionListener **)dub::checksdata(L, 1, "b2.b2DestructionListener"));
    int type__ = lua_type(L, 2);
    void **ptr2__;
    if ( (ptr2__ = dub::issdata(L, 2, "b2.b2Joint", type__)) ) {
      b2Joint *joint = *((b2Joint **)ptr2__);
      self->SayGoodbye(joint);
      return 0;
    } else {
      b2Fixture *fixture = *((b2Fixture **)dub::checksdata(L, 2, "b2.b2Fixture"));
      self->SayGoodbye(fixture);
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "SayGoodbye: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "SayGoodbye: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int b2DestructionListener___tostring(lua_State *L) {
  b2DestructionListener *self = *((b2DestructionListener **)dub::checksdata_n(L, 1, "b2.b2DestructionListener"));
  lua_pushfstring(L, "b2.b2DestructionListener: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg b2DestructionListener_member_methods[] = {
  { "__gc"         , b2DestructionListener__b2DestructionListener },
  { "SayGoodbye"   , b2DestructionListener_SayGoodbye },
  { "__tostring"   , b2DestructionListener___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_b2_b2DestructionListener(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "b2.b2DestructionListener");
  // <mt>

  // register member methods
  dub::fregister(L, b2DestructionListener_member_methods);
  // setup meta-table
  dub::setup(L, "b2.b2DestructionListener");
  // <mt>
  return 1;
}
